miniShop/miniShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using miniShop.Models;
using miniShop.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace miniShop.Controllers
{
    public class CartController : Controller
    {
        private IProductService productService;

        public CartController(IProductService productService)
        {
            this.productService = productService;
        }
        public IActionResult Index(string returnUrl)
        {
            var cart = GetCart();
            ViewBag.ReturnUrl = returnUrl;  
            return View(cart);
        }
        [HttpPost]
        public IActionResult AddToCart(int id, string returnUrl)
        {
            var selectedProduct = productService.GetProductById(id);
            if (selectedProduct == null)
            {
                return NotFound();

            }
            Cart cart = GetCart() ?? new Cart();
            cart.AddItem(selectedProduct, 1);
            SaveCart(cart);
            return RedirectToAction(nameof(Index), nameof(Cart), new { returnUrl= returnUrl }); // index yönlendir.
        }
        Cart GetCart()
        {
            var data = HttpContext.Session.GetString("Sepetim");
            if (data == null)
            {
                return null;
            }
            else
            {
                return JsonConvert.DeserializeObject<Cart>(data);
            }

        }

        void SaveCart(Cart cart)
        {
            HttpContext.Session.SetString("Sepetim", JsonConvert.SerializeObject(cart));
            
        
        }
    }
}

miniShop/miniShop/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using miniShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace miniShop.ViewComponents
{
    public class MenuViewComponent: ViewComponent
    {
        private ICategoryService categoryService;


        public MenuViewComponent(ICategoryService categoryService)
        {
           this.categoryService = categoryService;

        }
        public IViewComponentResult Invoke()
        {
            // ınvoke olmak zorunda 
            var categories = categoryService.GetCategories();
            return View(categories);

        }
    }
}

miniShop/miniShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - miniShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">miniShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">@await Component.InvokeAsync("Menu")</div>
                <div class="col-9">
                    @RenderBody()
                </div>
            </div>
        
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - miniShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

miniShop/miniShop/Views/Shared/_ProductCard.cshtml
@model Product
@{
    var request = ViewContext.HttpContext.Request;
    string returnUrlValue = request.QueryString.HasValue ?
        $"{request.Path}{request.QueryString}" : request.Path.Value;
}

<div class="card">
    <img src="@Model.ImageUrl" class="card-img-top" alt="Eşorfman">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
        <p class="card-text">@Model.Price</p>
        <p class="card-text">@Model.Price yerine @(Model.Price* (1- Model.Discount) )</p>
        <form asp-action="AddToCart" asp-controller="Cart"  asp-route-id="@Model.Id" method="post"  >
           
            <input type="hidden" name="returnUrl" value="@returnUrlValue" />
            <button type="submit" class="btn btn-primary">Sepete Ekle</button>
        </form>
    </div>
</div>